### ISSUE TITLE
Hard constrain applies only every second feature

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1461]
INPUT version: 0.9.7.
project: input-testing/form_derived

Hard constrain applies only on every 2nd feature.

https://user-images.githubusercontent.com/83582181/121015476-5384c300-c79b-11eb-9e20-29dce21e4dfe.mp4

**Comment by sklencar** [comment]
@jozef-budac Could you please confirm that the issue is present also on current master (or latest beta) version?
I couldn't replicate it and I think the bug has been already fixed. 

Note that Input still may have problem with numeric fields and setting null value all together with NOT NULL hard constrain.
Also note, that the **input-testing/form_derived** project has changed in meanwhile.

**Comment by jozef-budac** [comment]
Yes, the issue is still present in 0.9.9. version

You can test in on project tin1/issue
